//import products from "../seed-data/products";

export async function seed(knex) {
  // Deletes ALL existing entries
  await knex("products").del();
  await knex("products").insert([
    {
      id: 1,
      type: "Cleanser",
      time: "Day",
      concern: "Dryness",
      brand: "CeraVe",
      name: "Hydrating Cleanser",
      ingredient: "Ceramides",
      price: 19.99,
      photo: "images/cerave-cleanser.webp",
      photoDescription: "image of product",
      link: "https://www.walmart.ca/en/ip/cerave-hydrating-facial-cleanser-with-hyaluronic-acid-and-3-ceramides-gentle-moisturizing-non-foaming-facial-cleanser-for-men-women-daily-face-wash-fo/6000200706743",
    },
    {
      id: 2,
      type: "Toner",
      time: "Day",
      concern: "Dryness",
      brand: "Klairs",
      name: "Supple Preparation Unscented Toner",
      ingredient: "Sodium Hyaluronate",
      price: 28.99,
      photo: "images/klairs-toner.webp",
      photoDescription: "image of product",
      link: "https://kiokii.com/products/dear-klairs-supple-preparation-unscented-toner-180ml?srsltid=AfmBOopHC76zAMMpVqowR5FvuYYJrqea9br-2Q_LdorARzNItF7Q2Rkk",
    },
    {
      id: 3,
      type: "Serum",
      time: "Day",
      concern: "Dryness",
      brand: "The Ordinary",
      name: "Hyaluronic Acid 2% + B5",
      ingredient: "Hyaluronic Acid",
      price: 12.0,
      photo: "images/ordinary-hyaluronic.webp",
      photoDescription: "image of product",
      link: "https://www.sephora.com/ca/en/product/the-ordinary-hyaluronic-acid-2-b5-hydrating-serum-P427419",
    },
    {
      id: 4,
      type: "Moisturizer",
      time: "Day",
      concern: "Dryness",
      brand: "First Aid Beauty",
      name: "Ultra Repair Cream",
      ingredient: "Colloidal Oatmeal",
      price: 51.5,
      photo: "images/first-aid.webp",
      photoDescription: "image of product",
      link: "https://www.sephora.com/ca/en/product/P381145",
    },
    {
      id: 5,
      type: "SPF",
      time: "Day",
      concern: "Dryness",
      brand: "EltaMD",
      name: "UV Clear Broad-Spectrum SPF 46",
      ingredient: "Zinc Oxide",
      price: 70.0,
      photo: "images/eltamd-sunscreen.jpg",
      photoDescription: "image of product",
      link: "https://www.amazon.ca/EltaMD-Broad-Spectrum-Acne-Prone-Dermatologist-Recommended-Mineral-Based/dp/B002MSN3QQ/ref=sr_1_2?dib=eyJ2IjoiMSJ9.WNmp2TmxFjKUNVgZI2U59JglV3dhpKDkuLIxk5TXUBrWQ2VO48Fj1ZUjMMdFUuuO_HZfCRWofnQ7VgbDy67I_kod6RXv7JxMHu6R04xlT-eqEZNqFUEonOWZQQ4jyysDV4iHD47BrXlY9Q73EjSu0MvYV0skY3i8zzWS7cR6WuE7uzZgfCeIbFeX5hjK_fIXy6wMgBAzd4d6GSBoJjTdWbSG9xXdqZZDLj878pE7S-xJ2D9Nu-2HSIXHRZcgOTMeMsdz0DVFOvZ5X1JXDWk5OwMAm15_GCQ7_VboUL7HzJflO9xWUewqERML-TcUO2skuM-GpEu2NljRoAAlkydPyPZT98zeJjb2F4q1jF_NOaHaTjnf6cbkXsjHFrt3jePWsvlbqwZYVdLFlm-RizCaC4fIDO1Yt-pumvNNDswlX1smUTCe_ItxU_SmfLrbM35x.QUf6QpNmuDOQQNZrkkXP_-oIwLJW-ttnc_9zvU6l72U&dib_tag=se&hvadid=669891284048&hvdev=c&hvlocphy=9214505&hvnetw=g&hvqmt=e&hvrand=9929468984995936324&hvtargid=kwd-376192743729&hydadcr=8698_13663476&keywords=elta+md+sunscreen+for+face&qid=1736805851&sr=8-2",
    },
    {
      id: 6,
      type: "Sleeping Mask",
      time: "Night",
      concern: "Dryness",
      brand: "Laneige",
      name: "Water Sleeping Mask",
      ingredient: "Hydro Ionized Mineral Water",
      price: 43.5,
      photo: "images/laneige-mask.webp",
      photoDescription: "image of product",
      link: "https://www.sephora.com/ca/en/product/P479330",
    },
    {
      id: 7,
      type: "Cleanser",
      time: "Day",
      concern: "Acne",
      brand: "Neutrogena",
      name: "Oil-Free Acne Wash",
      ingredient: "Salicylic Acid",
      price: 11.99,
      photo: "images/neutrogena.webp",
      photoDescription: "image of product",
      link: "https://www.walmart.ca/en/ip/neutrogena-oil-free-acne-wash-with-salicylic-acid/10031465",
    },
    {
      id: 8,
      type: "Toner",
      time: "Day",
      concern: "Acne",
      brand: "Paula’s Choice",
      name: "Skin Perfecting 2% BHA Liquid Exfoliant",
      ingredient: "Salicylic Acid",
      price: 49.0,
      photo: "images/pc-toner.webp",
      photoDescription: "image of product",
      link: "https://www.sephora.com/ca/en/product/P511700",
    },
    {
      id: 9,
      type: "Serum",
      time: "Day",
      concern: "Acne",
      brand: "Caudalie",
      name: "Vinoperfect Radiance Serum Vitamin C Alternative",
      ingredient: "Vine Sap Viniferine",
      price: 110.0,
      photo: "images/vinoperfect.webp",
      photoDescription: "image of product",
      link: "https://www.sephora.com/ca/en/product/caudalie-vinoperfect-radiance-serum-vitamin-c-alternative-P510584?skuId=2748424&icid2=products%20grid:p510584:product",
    },
    {
      id: 10,
      type: "Moisturizer",
      time: "Day",
      concern: "Acne",
      brand: "La Roche-Posay",
      name: "Effaclar Mat Moisturizer",
      ingredient: "Sebulyse Technology",
      price: 29.95,
      photo: "images/effaclar.webp",
      photoDescription: "image of product",
      link: "https://www.shoppersdrugmart.ca/la-roche-posay-effaclar-mat-anti-shine-anti-enlarged-pores-daily/p/BB_3337872413025?variantCode=3337872413025",
    },
    {
      id: 11,
      type: "SPF",
      time: "Day",
      concern: "Acne",
      brand: "La Roche-Posay",
      name: "Anthelios Clear Skin SPF 60",
      ingredient: "Airlicium",
      price: 29.95,
      photo: "images/anthelios-sunscreen.webp",
      photoDescription: "image of product",
      link: "https://www.laroche-posay.ca/en_CA/anthelios-xl-dry-touch-spf-60-facial-sunscreen/3337875586115.html?srsltid=AfmBOoqWYJU4Z6__uuJqble720Pf4tbCwKBjTplAkXNvmBIJwZpsr7Pa",
    },
    {
      id: 12,
      type: "Mask",
      time: "Night",
      concern: "Acne",
      brand: "Innisfree",
      name: "Super Volcanic Pore Clay Mask 2X",
      ingredient: "Volcanic Clusters",
      price: 24.5,
      photo: "images/innisfree.webp",
      photoDescription: "image of product",
      link: "https://www.sephora.com/ca/en/product/innisfree-pore-clearing-clay-mask-P468658?skuId=2735777&icid2=products%20grid:p468658:product",
    },
    {
      id: 13,
      type: "Cleanser",
      time: "Day",
      concern: "Anti-Aging",
      brand: "Innisfree",
      name: "Cherry Blossom Glow Jam Cleanser",
      ingredient: "Cherry Blossom Extract and Betaine",
      price: 19.0,
      photo: "images/innisfree-cleanser.webp",
      photoDescription: "image of product",
      link: "https://www.sephora.com/ca/en/product/innisfree-cherry-blossom-glow-jam-cleanser-P482007?skuId=2740553&icid2=products%20grid:p482007:product",
    },
    {
      id: 14,
      type: "Toner",
      time: "Day",
      concern: "Anti-Aging",
      brand: "fresh",
      name: "Rose & Hyaluronic Acid Deep Hydration Toner",
      ingredient: "Rose Fruit Extract",
      price: 65.0,
      photo: "images/fresh.webp",
      photoDescription: "image of product",
      link: "https://www.sephora.com/ca/en/product/rose-deep-hydration-facial-toner-P417936?skuId=1924901&icid2=products%20grid:p417936:product",
    },
    {
      id: 15,
      type: "Serum",
      time: "Day",
      concern: "Anti-Aging",
      brand: "Olay",
      name: "Regenerist Max Wrinkle Serum",
      ingredient: "Retinol24",
      price: 39.99,
      photo: "images/olay.png",
      photoDescription: "image of product",
      link: "https://www.walmart.ca",
    },
    {
      id: 16,
      type: "Moisturizer",
      time: "Day",
      concern: "Anti-Aging",
      brand: "Paula's Choice",
      name: "Pro-Collagen Peptide Plumping Gel-Cream Moisturizer",
      ingredient: "Hexapeptide-5 (Water-Binding Peptide)",
      price: 66.0,
      photo: "images/pc-moisturizer.webp",
      photoDescription: "image of product",
      link: "https://www.sephora.com/ca/en/product/pro-collagen-peptide-plumping-gel-cream-moisturizer-P514886?skuId=2831774&icid2=products%20grid:p514886:product",
    },
    {
      id: 17,
      type: "SPF",
      time: "Day",
      concern: "Anti-Aging",
      brand: "Neutrogena",
      name: "Hydro Boost Water Gel Lotion Sunscreen SPF 30 with Hyaluronic Acid",
      ingredient: "Broad-Spectrum Sunscreen",
      price: 19.99,
      photo: "images/aging-sunscreen.jpg",
      photoDescription: "image of product",
      link: "https://www.shoppersdrugmart.ca",
    },
    {
      id: 18,
      type: "Mask",
      time: "Night",
      concern: "Anti-Aging",
      brand: "Kiehl's",
      name: "Ultra Facial Overnight Hydrating Face Mask",
      ingredient: "Squalane",
      price: 62.0,
      photo: "images/aging-mask.jpg",
      photoDescription: "image of product",
      link: "https://www.sephora.com/ca/en/product/P479329",
    },
    {
      id: 19,
      type: "Cleanser",
      time: "Day",
      concern: "Oiliness",
      brand: "Tatcha",
      name: "The Matcha Cleanse Daily Clarifying Gel Cleanser",
      ingredient: "BHA Botanical Alternatives",
      price: 54.0,
      photo: "images/tatcha_cleanser.webp",
      photoDescription: "image of tatcha cleanser",
      link: "https://www.sephora.com/ca/en/product/tatcha-the-matcha-cleanse-daily-clarifying-gel-cleanser-P509955?skuId=2750065&icid2=products%20grid:p509955:product",
    },
    {
      id: 20,
      type: "Toner",
      time: "Day",
      concern: "Oiliness",
      brand: "ilso",
      name: "Super Melting Sebum Softener",
      ingredient: "Polygonum Cuspidatum Root Extract",
      price: 34.99,
      photo: "images/ilso.webp",
      photoDescription: "image of product",
      link: "https://kiokii.com/collections/facial-oils/products/super-melting-sebum-softener-150g",
    },
    {
      id: 21,
      type: "Serum",
      time: "Day",
      concern: "Oiliness",
      brand: "The Ordinary",
      name: "Niacinamide 10% + Zinc 1% Oil Control Serum",
      ingredient: "Niacinamide",
      price: 6.6,
      photo: "images/ordinary_serum.webp",
      photoDescription: "image of product",
      link: "https://www.sephora.com/ca/en/product/the-ordinary-deciem-niacinamide-10-zinc-1-P427417?skuId=2031391&icid2=products%20grid:p427417:product",
    },
    {
      id: 22,
      type: "Mask",
      time: "Day",
      concern: "Oiliness",
      brand: "Caudalie",
      name: "Pore Minimizing Instant Detox Mask",
      ingredient: "Grape Seed Polyphenols",
      price: 56.0,
      photo: "images/caudalie-mask.webp",
      photoDescription: "image of product",
      link: "https://www.sephora.com/ca/en/product/instant-detox-mask-P395615?skuId=1698018&icid2=products%20grid:p395615:product",
    },
    {
      id: 23,
      type: "Moisturizer",
      time: "Day",
      concern: "Oiliness",
      brand: "Drunk Elephant",
      name: "Protini™ Polypeptide Firming Refillable Moisturizer",
      ingredient: "Signal Peptide Complex",
      price: 92.0,
      photo: "images/drunk-elephant-cream.webp",
      photoDescription: "image of product",
      link: "https://www.sephora.com/ca/en/product/protini-tm-polypeptide-cream-P427421?skuId=2025633&icid2=products%20grid:p427421:product",
    },
    {
      id: 24,
      type: "SPF",
      time: "Day",
      concern: "Oiliness",
      brand: "Sheiseido",
      name: "Urban Environment Vita-Clear Sunscreen SPF 42",
      ingredient: "Hypotaurine",
      price: 51.5,
      photo: "images/shiseido_sunscreen.webp",
      photoDescription: "image of product",
      link: "https://www.sephora.com/ca/en/product/urban-environment-vita-clear-sunscreen-spf-42-P505212?skuId=2673382&icid2=products%20grid:p505212:product",
    },
  ]);
}
